name: CI + CD

on:
  push:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Write SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy to EC2
        run: |
          scp -i key.pem -o StrictHostKeyChecking=no -r *.py requirements.txt ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/calculadora/
          ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/calculadora
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart calculadora.service
          EOF
